SELECT 
    A.SID, A.USERNAME, A.MACHINE, A.TERMINAL, C.ADDRESS, C.LAST_ACTIVE_TIME, 
    C.LAST_LOAD_TIME, C.SQL_TEXT
FROM
    V$SESSION A, V$ACCESS B, V$SQL C
WHERE
    A.SERVICE_NAME = C.SERVICE AND A.SID = B.SID AND A.PREV_SQL_ID = C.SQL_ID AND C.SERVICE = A.SERVICE_NAME;