--step 1 일반적 GROUP BY 절 사용
SELECT DNAME, JOB,
  COUNT(*) "Total Empl",
  SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DNAME, JOB;

--step 1-2 GROUP BY 절 + ORDER BY 절 사용
SELECT DNAME, JOB,
  COUNT(*) "Total Empl",
  SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DNAME, JOB
ORDER BY DNAME, JOB;

--step 2 ROLLUP 함수 사용
SELECT DNAME, JOB,
  COUNT(*) "Total Empl",
  SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP(DNAME, JOB);

--step 2-2 ROLLUP 함수 + ORDER BY 절 사용
SELECT DNAME, JOB,
  COUNT(*) "Total Empl",
  SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP (DNAME, JOB)
ORDER BY DNAME, JOB;

--step 3 GROUPING 함수 사용
SELECT DNAME, GROUPING(DNAME),
  JOB, GROUPING(JOB),
  COUNT(*) "Total Empl",
  SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP(DNAME, JOB);

--step 4 GROUPING 함수 + CASE 사용
SELECT
  CASE GROUPING(DNAME) WHEN 1 THEN 'All Departments' ELSE DNAME END AS DNAME,
  CASE GROUPING(JOB) WHEN 1 THEN 'All Jobs' ELSE JOB END AS JOB,
  COUNT(*) "Total Empl",
  SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP(DNAME, JOB);
--Oracle의 경우는 DECODE 함수를 사용해서 좀더 짧게 표현할 수 있다.
SELECT
  DECODE(GROUPING(DNAME), 1, 'All Departments', DNAME) AS DNAME,
  DECODE(GROUPING(JOB), 1, 'All Jobs', JOB) AS JOB,
  COUNT(*) "Total Empl",
  SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP(DNAME, JOB);

--step 4-2 ROLLUP 함수 일부 사용
SELECT
 CASE GROUPING(DNAME) WHEN 1 THEN 'All Departments' ELSE DNAME END AS DNAME,
 CASE GROUPING(JOB) WHEN 1 THEN 'All Jobs' ELSE JOB END AS JOB,
 COUNT(*) "Total Empl",
 SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DNAME, ROLLUP(JOB);

--step 4-3 ROLLUP 함수 결합 컬럼 사용
SELECT DNAME, JOB, MGR, SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY ROLLUP(DNAME, (JOB, MGR));

--step 5 CUBE 함수 이용
SELECT
  CASE GROUPING(DNAME) WHEN 1 THEN 'All Departments' ELSE DNAME END AS DNAME,
  CASE GROUPING(JOB) WHEN 1 THEN 'All Jobs' ELSE JOB END AS JOB,
  COUNT(*) "Total Empl",
  SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY CUBE (DNAME, JOB);

--step 5-2 UNION ALL 사용 SQL
SELECT DNAME, JOB, COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DNAME, JOB
UNION ALL
SELECT DNAME, 'All Jobs', COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DNAME
UNION ALL
SELECT 'All Departments', JOB, COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY JOB
UNION ALL
SELECT 'All Departments', 'All Jobs', COUNT(*) "Total Empl",
  SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO;

--일반 그룹함수를 이용한 SQL
SELECT DNAME, 'All Jobs' JOB, COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DNAME
UNION ALL
SELECT 'All Departments' DNAME, JOB, COUNT(*) "Total Empl",
  SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY JOB;

--GROUPING SETS 사용 SQL
SELECT DECODE(GROUPING(DNAME), 1, 'All Departments', DNAME) AS DNAME,
  DECODE(GROUPING(JOB), 1, 'All Jobs', JOB) AS JOB,
  COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY GROUPING SETS(DNAME, JOB);

--GROUPING SETS 사용 SQL - 순서 변경
SELECT DECODE(GROUPING(DNAME), 1, 'All Departments', DNAME) AS DNAME,
  DECODE(GROUPING(JOB), 1, 'All Jobs', JOB) AS JOB,
  COUNT(*) "Total Empl", SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY GROUPING SETS(JOB, DNAME);

--3개의 인수를 이용한 GROUPING SETS 이용
SELECT DNAME, JOB, MGR, SUM(SAL) "Total Sal"
FROM EMP, DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY GROUPING SETS
((DNAME, JOB, MGR), (DNAME, JOB), (JOB, MGR));
