CREATE TABLE `USERS` (
  `USER_ID` varchar(100) NOT NULL DEFAULT '',
  `USER_NAME` varchar(100) DEFAULT NULL,
  `USER_PASSWORD` varchar(3) DEFAULT NULL,
  `CRT_DT` timestamp NULL DEFAULT NULL,
  `MDFY_DT` timestamp NULL DEFAULT NULL,
  `LOGIN_FAIL_COUNT` decimal(10,0) DEFAULT '0',
  `IS_ACCOUNT_LOCK` char(1) DEFAULT 'N',
  `LATEST_LOGIN_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


SELECT * from USERS;

